services:
  - type: web
    name: eevi-verite
    runtime: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      npm ci
      npm run build
    startCommand: gunicorn app:app
    plan: free
