# === render.yaml ===
services:
  - name: eevi-api
    type: web
    runtime: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      npm install --legacy-peer-deps
      npm run build
      mkdir -p static
      cp -r dist/* static/
    startCommand: gunicorn -k gevent -w 3 app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        value: "PASTE_YOUR_COMPACT_JSON_HERE"
      - key: VITE_CHAT_URL
        value: "https://eevi-chat.onrender.com"

  - name: eevi-chat
    type: web
    runtime: node
    plan: free
    buildCommand: |
      npm install
    startCommand: node server/chatServer.js
    envVars: []
