name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Verificar Firestore
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=serviceAccountKey.json
          python scripts/firebase_init.py
      - name: Run tests
        run: pytest -q
